version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://localhost:3000
    ports:
      - "80:80"
  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"